[package]
name = "prefade-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "_prefade_native"
crate-type = ["cdylib"]

[dependencies]
prefade-core = { path = "../core" }
pyo3 = { version = "0.22", features = ["extension-module"] }
