[package]
name = "prefade-lua"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
prefade-core = { path = "../core" }
mlua = { version = "0.10", features = ["lua54", "module"] }
